In [2]:
import numpy as np
import time

In [3]:

# NumPy Arrays vs Python Lists - Execution time comparison

# large dataset
size = 10_000_000  # 10 million numbers

# Python Lists
python_list = list(range(size))

start = time.time()
list_squared = [x**2 for x in python_list]  # square of all nums
end = time.time()
print("Python list time:", end - start, "seconds")

# NumPy Arrays
numpy_array = np.array(python_list)
start = time.time()
array_squared = numpy_array ** 2  # vectorized operation
end = time.time()
print("NumPy array time:", end - start, "seconds")

Python list time: 0.8883090019226074 seconds
NumPy array time: 0.03477168083190918 seconds


In [11]:
#create from lists
arr = np.array([1,2,3,4,5])
print(arr,type(arr),arr.shape)

arr2 = np.array([1,2,3,4,5,"Janvi"])
print(arr2,type(arr2),arr2.dtype)

arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'Janvi'] <class 'numpy.ndarray'> <U21
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [32]:
#create
arr1 = np.zeros((2,3),dtype="int64")#prefill
print(arr1,arr1.shape)

arr3 = np.ones((5,))#prefill
print(arr3,arr3.shape)

arr4 = np.full((3,3),100)#prefill with val
print(arr4,arr4.shape)

arr5 = np.eye(3,dtype="int64")#identity matrix
print(arr5,arr5.shape)

arr6 = np.arange(0,11,2)#using range function
print(arr6,arr6.shape)

arr7 = np.linspace(1,100,3)#evenly spaced array
print(arr7,arr7.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100]
 [100 100 100]
 [100 100 100]] (3, 3)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.   50.5 100. ] (3,)


In [37]:
#prperties
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)
float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [42]:
#operations on arrays
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped= arr.reshape((3,2))
print(reshaped,reshaped.shape)

flattened = arr.flatten()     #2D=>1D
print(flattened,flattened.shape,flattened.ndim)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,) 1


In [55]:
#indexing
# arr= np.array([1,2,3,4,5,6])
# print(arr[0])
# print(arr[4])
# arr1=np.array([[1,2],[4,5]])
# print(arr1[0,0])

#fancy indexing
# arr= np.array([1,2,3,4,5,6])
# idx=[0,1,2]
# print(arr[idx])

#boolean indexing
arr= np.array([1,2,3,4,5,6])
print(arr[arr >2])
print(arr[arr %2==0])
print(arr[arr %2!=0])

[3 4 5 6]
[2 4 6]
[1 3 5]


#slicing operation


In [63]:
#slicing operation
arr= np.array([1,2,3,4,5,6])
# print(arr[0:5])
# print(arr[:5])
# print(arr[2:])
# print(arr[::2])


# Copy vs View by Slicing
#Sliced list is a copy
py_list = [1, 2, 3, 4, 5]
copy_list = py_list[1:4] #[2, 3, 4]
copy_list[1] = 333

print(copy_list)
print(py_list)

#Sliced array is a view
np_arr = np.array([1, 2, 3, 4, 5])
view_arr = np_arr[1:4] #[2, 3, 4]
view_arr[1] = 333

print(view_arr)
print(np_arr)

#Creating a copy
copy_arr = np_arr[1:4].copy() #[2, 3, 4]
copy_arr[2] = 444
print(copy_arr)
print(np_arr)

[2, 333, 4]
[1, 2, 3, 4, 5]
[  2 333   4]
[  1   2 333   4   5]
[  2 333 444]
[  1   2 333   4   5]


In [13]:
#numpy datatypes
import numpy as np
arr=np.array([1,2,3.14,4,5])
print(arr,arr.dtype)

arr1=np.array([2 + 3j])
print(arr1,arr1.dtype)

arr2=np.array([5+2j])
print(arr1 + arr2)
print(arr1 - arr2)

[1.   2.   3.14 4.   5.  ] float64
[2.+3.j] complex128
[7.+5.j]
[-3.+1.j]


In [23]:
#multi darray
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D))

sum_of_columns=np.sum(arr2D,axis = 0)
print(sum_of_columns)
print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[[2]
 [5]]


In [17]:
import numpy as np
arr3D = np.array([[[1,2],[3,4],[4,5]],[[6,7],[8,9],[10,11]]])#2*3*2
print(arr3D,arr3D.shape)
#indexing 
print(arr3D[1,2,0])
#slicing
print(arr3D[:,0,:])#first row from both layers
print(arr3D[:,:,0])#first col from both layers
arr3D[:,0,:]=45
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] (2, 3, 2)
10
[[1 2]
 [6 7]]
[[ 1  3  4]
 [ 6  8 10]]
[[[45 45]
  [ 3  4]
  [ 4  5]]

 [[45 45]
  [ 8  9]
  [10 11]]]


In [26]:
#vectoriztaion
arr=np.array([4,5,6,7,8])
print(arr**2)
arr1=np.array([12,1,40,2,2])
print(arr+arr1)
              

[16 25 36 49 64]
[16  6 46  9 10]


In [31]:
#broadcasting-streching the values compatible to equivalent array
print(arr+5)
arr=np.array([4,5,6,7,8])
arr1=np.array([[12,1,40,2,2],[4,5,6,7,8]])
print(arr.shape,arr.size)
print(arr1.shape,arr1.size)
print(arr+arr1)

[ 9 10 11 12 13]
(5,) 5
(2, 5) 10
[[16  6 46  9 10]
 [ 8 10 12 14 16]]


In [38]:
#normalization
arr=np.array([[4,5],[7,8]])
mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)
print(mean)
print(std_dev)

[[-1.26491106 -0.63245553]
 [ 0.63245553  1.26491106]]
6.0
1.5811388300841898




### Mathematical Functions in NumPy
There are lots of important & commonly used mathematical functions in NumPy
1. Aggregation functions
   - sum()
   - prod()
   - min() & argmin() - min val & idx of min val
   - max() & argmax() - max val & idx of max val
   - mean()
   - median()
   - std() - standard deviation
   - var() - variance

In [42]:
# Mathematical Functions

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))     # 15
print(np.prod(arr))    # 120
print(np.min(arr))     # 1
print(np.argmin(arr))  # 0
print(np.max(arr))     # 5
print(np.argmax(arr))  # 4
print(np.mean(arr))    # 3.0
print(np.median(arr))  # 3.0
print(np.std(arr))     # 1.41
print(np.var(arr))     # 2.0

15
120
1
0
5
4
3.0
3.0
1.4142135623730951
2.0


2. Power functions
   - square()
   - sqrt() - square root
   - pow(a, b) - a^b

In [43]:
print(np.square(arr))    # [1, 4, 9, 16, 25]
print(np.sqrt(arr))      # [1, 1.41, 1.73, 2, 2.23]
print(np.pow(arr, 3))    # [1, 8, 27, 64, 125]

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


3. Log & Exponential functions
   - log() - natual log
   - log10() - log base 10
   - log2() - log base 2
   - exp() - exponentional i.e. e^x

In [45]:
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))


[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


4. Rounding functions
   - round() - rounds to nearest value
   - floor() - rounds down
   - ceil() - rounds up
   - trunc() - truncates decimal part

In [46]:
print(np.round(2.678))    # 3.0
print(np.floor(2.678))    # 2.0
print(np.ceil(2.678))     # 3.0
print(np.trunc(2.678))    # 2.0

3.0
2.0
3.0
2.0


5. Additional functions
   - abs() - absolute value
   - sort()
   - unique() - returns unique values

+ there are additionally a lot more useful functions that we'll study later.

In [47]:
arr = np.array([1, 2, -5, 3, 8, -4, 2, 5])
print(np.abs(arr))     # [1 2 5 3 8 4 2 5]
print(np.sort(arr))    # [-5 -4  1  2  2  3  5  8]
print(np.unique(arr))  # [-5 -4  1  2  3  5  8]

[1 2 5 3 8 4 2 5]
[-5 -4  1  2  2  3  5  8]
[-5 -4  1  2  3  5  8]
